/// Flutter icons Material
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Material
///      fonts:
///       - asset: fonts/Material.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ls {
  ls._();

  static const _kFontFam = 'Mtri';
  static const String? _kFontPkg = null;

  static const IconData out = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_center = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
