/// Flutter icons Material
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Material
///      fonts:
///       - asset: fonts/Material.ttf
///
///
///
import 'package:flutter/widgets.dart';

class icon {
  icon._();

  static const _kFontFam = 'Material';
  static const String? _kFontPkg = null;

  static const IconData fluent_emoji_high_contrast_baby_angel = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
