/// Flutter icons Material
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Material
///      fonts:
///       - asset: fonts/user_profile_icon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Search {
  Search._();

  static const _kFontFam = 'Material2';
  static const String? _kFontPkg = null;

  static const IconData icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
