/// Flutter icons Material
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Material
///      fonts:
///       - asset: fonts/Material.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ThemeIcons {
  ThemeIcons._();

  static const _kFontFam = 'Mt';
  static const String? _kFontPkg = null;

  static const IconData moon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
